import{AiOutlineEdit} from "react-icons/ai"
import { FiUserPlus } from "react-icons/fi";

const rows = [
  {
    id: 1,
    name: "Abijith",
    client: "1330",
    email: "abijithstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active: <FiUserPlus />,
    action: <AiOutlineEdit />,
  },
  {
    id: 2,
    name: "Bhuvana",
    client: "1330",
    email: "bhuvanastreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 3,
    name: "Nikila",
    client: "1330",
    email: "nikilastreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "offline",
    category: "BD",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 4,
    name: "Habirami",
    client: "1330",
    email: "habiramistreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "SHR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 5,
    name: "Elakiyan",
    client: "1330",
    email: "elakiyanstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "HR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 6,
    name: "Arun",
    client: "1330",
    email: "arunstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "IHR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 7,
    name: "Dheena",
    client: "1330",
    email: "dheenastreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 8,
    name: "Akash",
    client: "1330",
    email: "akashstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 9,
    name: "Naveen",
    client: "1330",
    email: "naveenstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 10,
    name: "Kesavan",
    client: "1330",
    email: "kesavanstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 11,
    name: "Vishnu",
    client: "1330",
    email: "vishnustreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 12,
    name: "Manoj ",
    client: "1330",
    email: "manojkumarstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 13,
    name: "Arun ",
    client: "1330",
    email: "arunprakashstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 14,
    name: "Reshami",
    client: "1330",
    email: "reshamistreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "HR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 15,
    name: "Gayathri",
    client: "1330",
    email: "gayathristreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "HR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 16,
    name: "Abijith",
    client: "1330",
    email: "abijithstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 17,
    name: "Bhuvana",
    client: "1330",
    email: "bhuvanastreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 18,
    name: "Nikila",
    client: "1330",
    email: "nikilastreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "BD",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 19,
    name: "Habirami",
    client: "1330",
    email: "habiramistreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "SHR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 20,
    name: "Elakiyan",
    client: "1330",
    email: "elakiyanstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "HR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 21,
    name: "Arun",
    client: "1330",
    email: "arunstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "IHR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 22,
    name: "Dheena",
    client: "1330",
    email: "dheenastreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 23,
    name: "Akash",
    client: "1330",
    email: "akashstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 24,
    name: "Naveen",
    client: "1330",
    email: "naveenstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 25,
    name: "Kesavan",
    client: "1330",
    email: "kesavanstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 26,
    name: "Vishnu",
    client: "1330",
    email: "vishnustreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 27,
    name: "Manoj ",
    client: "1330",
    email: "manojkumarstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 28,
    name: "Arun ",
    client: "1330",
    email: "arunprakashstreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "FED",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 29,
    name: "Reshami",
    client: "1330",
    email: "reshamistreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "HR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
  {
    id: 30,
    name: "Gayathri",
    client: "1330",
    email: "gayathristreams@gmail.com",
    contact: "1234567891",
    net: "-",
    termination: "-",
    status: "online",
    category: "HR",
    additional: "-",
    active:<FiUserPlus />,
    action:<AiOutlineEdit />,
  },
];

export default rows;